// <auto-generated />
namespace SensorsManager.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ProductionDateForGatewayAndNetwork : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProductionDateForGatewayAndNetwork));
        
        string IMigrationMetadata.Id
        {
            get { return "201906040917396_ProductionDateForGatewayAndNetwork"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
